name: CI
on:
  pull_request:
    branches: [ develop ]
  workflow_dispatch:

env:
  JAVA_VERSION: "12.x"
  FLUTTER_VERSION: "3.19.1"

jobs:
  UT_format_lint_notify:
    name: Check format, lint and tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: ${{env.JAVA_VERSION}}
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{env.FLUTTER_VERSION}}

      - name: Add pub cache bin to PATH
        run: echo "$HOME/.pub-cache/bin" >> $GITHUB_PATH

      - name: Add pub cache to PATH
        run: echo "PUB_CACHE="$HOME/.pub-cache"" >> $GITHUB_ENV

      - name: Run pub get and gen files
        run: make sync

      - name: Run check_pubspecs
        run: make check_pubs

      - name: Run Tests
        run: make te

      - name: Check format
        run: make fm

      - name: Run lint
        run: make lint

      # - uses: mechiru/chatwork@v2
      #   with:
      #     roomId: 251400100
      #     token: ${{ secrets.CHATWORK_API_TOKEN }}
